//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Email Template</summary>
	[PublishedContentModel("emailTemplate")]
	public partial class EmailTemplate : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "emailTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EmailTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EmailTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cc Listing
		///</summary>
		[ImplementPropertyType("emailTemplateCcListing")]
		public string EmailTemplateCcListing
		{
			get { return this.GetPropertyValue<string>("emailTemplateCcListing"); }
		}

		///<summary>
		/// Email Template Code
		///</summary>
		[ImplementPropertyType("emailTemplateCode")]
		public string EmailTemplateCode
		{
			get { return this.GetPropertyValue<string>("emailTemplateCode"); }
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("emailTemplateEmailBody")]
		public IHtmlString EmailTemplateEmailBody
		{
			get { return this.GetPropertyValue<IHtmlString>("emailTemplateEmailBody"); }
		}

		///<summary>
		/// Recipient Email
		///</summary>
		[ImplementPropertyType("emailTemplateRecipientEmail")]
		public string EmailTemplateRecipientEmail
		{
			get { return this.GetPropertyValue<string>("emailTemplateRecipientEmail"); }
		}

		///<summary>
		/// Sender Email
		///</summary>
		[ImplementPropertyType("emailTemplateSenderEmail")]
		public string EmailTemplateSenderEmail
		{
			get { return this.GetPropertyValue<string>("emailTemplateSenderEmail"); }
		}

		///<summary>
		/// Sender Name
		///</summary>
		[ImplementPropertyType("emailTemplateSenderName")]
		public string EmailTemplateSenderName
		{
			get { return this.GetPropertyValue<string>("emailTemplateSenderName"); }
		}

		///<summary>
		/// Subject
		///</summary>
		[ImplementPropertyType("emailTemplateSubject")]
		public string EmailTemplateSubject
		{
			get { return this.GetPropertyValue<string>("emailTemplateSubject"); }
		}
	}
}
