//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email Verify Hash
		///</summary>
		[ImplementPropertyType("emailVerifyHash")]
		public string EmailVerifyHash
		{
			get { return this.GetPropertyValue<string>("emailVerifyHash"); }
		}

		///<summary>
		/// Facebook User Id
		///</summary>
		[ImplementPropertyType("facebookUserId")]
		public string FacebookUserId
		{
			get { return this.GetPropertyValue<string>("facebookUserId"); }
		}

		///<summary>
		/// Has Verified Email
		///</summary>
		[ImplementPropertyType("hasVerifiedEmail")]
		public bool HasVerifiedEmail
		{
			get { return this.GetPropertyValue<bool>("hasVerifiedEmail"); }
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("memberAddress")]
		public string MemberAddress
		{
			get { return this.GetPropertyValue<string>("memberAddress"); }
		}

		///<summary>
		/// Amka Number
		///</summary>
		[ImplementPropertyType("memberAmkaNumber")]
		public string MemberAmkaNumber
		{
			get { return this.GetPropertyValue<string>("memberAmkaNumber"); }
		}

		///<summary>
		/// Date Of Birth
		///</summary>
		[ImplementPropertyType("memberDateOfBirth")]
		public DateTime MemberDateOfBirth
		{
			get { return this.GetPropertyValue<DateTime>("memberDateOfBirth"); }
		}

		///<summary>
		/// D.O.Y
		///</summary>
		[ImplementPropertyType("memberDoy")]
		public string MemberDoy
		{
			get { return this.GetPropertyValue<string>("memberDoy"); }
		}

		///<summary>
		/// Identity Number
		///</summary>
		[ImplementPropertyType("memberIdentityNumber")]
		public string MemberIdentityNumber
		{
			get { return this.GetPropertyValue<string>("memberIdentityNumber"); }
		}

		///<summary>
		/// Member Is Over 18
		///</summary>
		[ImplementPropertyType("memberIsOver18")]
		public bool MemberIsOver18
		{
			get { return this.GetPropertyValue<bool>("memberIsOver18"); }
		}

		///<summary>
		/// Member Language
		///</summary>
		[ImplementPropertyType("memberLanguage")]
		public string MemberLanguage
		{
			get { return this.GetPropertyValue<string>("memberLanguage"); }
		}

		///<summary>
		/// Mobile Phone
		///</summary>
		[ImplementPropertyType("memberMobilePhone")]
		public string MemberMobilePhone
		{
			get { return this.GetPropertyValue<string>("memberMobilePhone"); }
		}

		///<summary>
		/// Postal Code
		///</summary>
		[ImplementPropertyType("memberPostalCode")]
		public int MemberPostalCode
		{
			get { return this.GetPropertyValue<int>("memberPostalCode"); }
		}

		///<summary>
		/// Vat Number
		///</summary>
		[ImplementPropertyType("memberVatNumber")]
		public string MemberVatNumber
		{
			get { return this.GetPropertyValue<string>("memberVatNumber"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}
}
